MCU := RP2040
BOOTLOADER := rp2040
BOARD = GENERIC_PROMICRO_RP2040
WS2812_DRIVER = vendor
SERIAL_DRIVER = vendor
LTO_ENABLE      = yes
CONSOLE_ENABLE = yes         # Console for debug
COMMAND_ENABLE = no			# Commands for debug and configuration
MIDI_ENABLE = no            # MIDI controls
AUDIO_ENABLE = no           # Audio output on port C6
MAGIC_ENABLE = yes
BACKLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = lite
TERMINAL_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
VIA_ENABLE      = yes

GRAVE_ESC_ENABLE = yes
SPACE_CADET_ENABLE = no

NKRO_ENABLE = yes

SPLIT_KEYBOARD = yes

DEBOUNCE_TYPE = asym_eager_defer_pk
SRC += ./rgb.c
