OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
VIA_ENABLE = yes
BOOTMAGIC_ENABLE = lite      # Enable Bootmagic Lite
EXTRAKEY_ENABLE            = yes      # Audio control and System control
COMMAND_ENABLE             = no       # Commands for debug and configuration
NKRO_ENABLE                = yes      # USB Nkey Rollover
OLED_ENABLE                = yes
ENCODER_ENABLE             = yes      # Enables the use of one or more encoders
RGBLIGHT_ENABLE            = no       # Enable keyboard RGB underglow
KEY_LOCK_ENABLE            = no
WPM_ENABLE                 = no
RGB_MATRIX_ENABLE      = yes
CONSOLE_ENABLE         = yes      # Console for debug
MOUSEKEY_ENABLE        = yes      # Mouse keys
TAP_DANCE_ENABLE       = no
SWAP_HANDS_ENABLE      = yes
LTO_ENABLE             = no
ENCODER_MAP_ENABLE     = yes
GRAVE_ESC_ENABLE = no
SPLIT_KEYBOARD = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
